version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    env_file:
      - env/.env.dev

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: devdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
      MYSQL_ROOT_PASSWORD: devroot
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql

volumes:
  mysql_data_dev:
